export const USER_TYPES = {
  FILTERS: 'USERS_FILTERS',
  PAGINATION: 'USERS_PAGINATION'
}

export const CLIENTS_TYPES = {
  FILTERS: 'CLIENTS_FILTERS',
  PAGINATION: 'CLIENTS_PAGINATION'
}

export const ARTICLES_TYPES = {
  FILTERS: 'ARTICLES_FILTERS',
  PAGINATION: 'ARTICLES_PAGINATION'
}

export const RECEIPTS_TYPES = {
  FILTERS: 'RECEIPTS_FILTERS',
  PAGINATION: 'RECEIPTS_PAGINATION'
}

export const OFFICES_TYPES = {
  FILTERS: 'OFFICES_FILTERS',
  PAGINATION: 'OFFICES_PAGINATION'
}

export default {
  ...USER_TYPES,
  ...CLIENTS_TYPES,
  ...ARTICLES_TYPES,
  ...OFFICES_TYPES
}
